services:
  web:
    platform: "linux/amd64"
    build:
      context: .
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:postgres@database/nwspk_development"
      REDIS_URL: "redis://redis:6379/0"
      SECRET_KEY_BASE: "xxx"
      CANONICAL_URL: "http://localhost:3000"
      SEND_REMINDERS: 1
      SMTP_PASSWORD: "xxx"
      SMTP_SERVER: "smtp.mailgun.org"
      SMTP_USER: "xxx"
      STRIPE_KEY: "sk_xxx"
      STRIPE_PUBLIC_KEY: "pk_xxx"
      STRIPE_TAX_RATE_ID: "txr_xxx"
      STRIPE_WEBHOOK_SECRET: "whsec_xxx"

  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
      timeout: 10s
      retries: 120
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    platform: "linux/amd64"
    image: redis:5.0

  sidekiq:
    platform: "linux/amd64"
    build:
      context: .
    depends_on:
      - web
      - database
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    environment:
      RAILS_ENV: development
      REDIS_URL: "redis://redis:6379/0"
    entrypoint: ./sidekiq-entrypoint.sh

volumes:
  gem_cache:
  postgres_data:
