Stripe.api_key = ENV['STRIPE_KEY'] || ''

STRIPE_PUBLIC_KEY = ENV['STRIPE_PUBLIC_KEY'] || ''
STRIPE_TAX_RATE_ID = ENV['STRIPE_TAX_RATE_ID'] || ''
STRIPE_WEBHOOK_SECRET = ENV['STRIPE_WEBHOOK_SECRET'] || ''
